---
name: lint

on:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install pre-commit
      - run: pre-commit run --all-files --show-diff-on-failure
